openapi: 3.0.0
info:
  title: The Social CRM - Integration Specifications
  version: '1.0'
  description: |-
    The CRM and Zeoniq sytem integration

    We use API keys as the secure key to access The Social CRM.
    Please get in touch with us to request a apiKey.
  contact:
    name: Duong Nguyen
    email: nhduong29@gmail.com
servers:
  - url: 'https://thesocial.stoplight.io/mocks/thesocial/thesocial-zeoniq/2252264'
paths:
  /customer:
    get:
      summary: Get Customer Information
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: &ref_3
                description: ''
                type: object
                title: Customer
                x-examples:
                  example-1:
                    cardNumber: '123456'
                    phoneNumber: '+61123456789'
                    email: test@gmail.com
                    name: User1
                    accountNumber: '123456'
                    pointBalance: 980
                    creditBalance: 985.2
                    tier: GOLD
                    vouchers:
                      - voucherID: v0123
                        voucherName: RM50 off the bill
                        value: 0
                        voucherType: Cash Voucher
                properties:
                  cardNumber:
                    type: string
                    minLength: 1
                  phoneNumber:
                    type: string
                    minLength: 1
                  email:
                    type: string
                    minLength: 1
                  name:
                    type: string
                    minLength: 1
                  accountNumber:
                    type: string
                    minLength: 1
                  pointBalance:
                    type: number
                  creditBalance:
                    type: number
                  tier:
                    type: string
                    minLength: 1
                  vouchers:
                    type: array
                    description: List all of vouchers that this user have
                    items: &ref_0
                      title: Voucher
                      type: object
                      description: Voucher of Customer
                      x-examples:
                        example-1:
                          voucherID: string
                          voucherName: string
                          value: 0
                          voucherType: string
                      properties:
                        voucherID:
                          type: string
                        voucherName:
                          type: string
                        value:
                          type: number
                        voucherType:
                          type: string
                        expiryDate:
                          type: string
                required:
                  - cardNumber
                  - phoneNumber
                  - email
                  - name
                  - accountNumber
                  - pointBalance
                  - creditBalance
                  - tier
              examples:
                example-1:
                  value:
                    cardNumber: string
                    phoneNumber: string
                    email: string
                    name: string
                    accountNumber: string
                    pointBalance: 0
                    creditBalance: 0
                    tier: string
                    vouchers:
                      - voucherID: string
                        voucherName: string
                        value: 0
                        voucherType: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errorCode:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - errorCode
                  - message
              examples:
                example-1:
                  value:
                    errorCode: ACC-NOT-FOUND
                    message: Accound not found
      operationId: get-customer
      parameters:
        - schema:
            type: string
          in: query
          name: cardNumber
          required: true
          description: Account number of Customer
      description: Get customer informations by accountNumber
      security:
        - Authorization apiKey: []
  /submit-sale:
    post:
      summary: Submit a sale data to CRM
      operationId: post-submit-sale
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  pointBalance:
                    type: number
                  creditBalance:
                    type: number
                  remarks:
                    type: string
                    minLength: 1
                  pointEarned:
                    type: number
                  pointRedeemed:
                    type: number
                required:
                  - pointBalance
                  - creditBalance
                  - remarks
              examples:
                example-1:
                  value:
                    pointBalance: 0
                    creditBalance: 0
                    remarks: string
                    pointEarned: 0
                    pointRedeemed: 0
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errorCode:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - errorCode
                  - message
              examples:
                example-1:
                  value:
                    errorCode: SUBMIT-SALE-ERROR
                    message: Can't submit sale...
      description: >-
        POS submit the transaction info to the CRM to check status, check
        points, credit
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                receiptID:
                  type: string
                  minLength: 1
                orderID:
                  type: string
                  minLength: 1
                posNo:
                  type: string
                  minLength: 1
                  description: POS number
                billDate:
                  type: string
                  minLength: 1
                groundTotal:
                  type: number
                  description: Total price after tax
                taxAmount:
                  type: number
                  description: Total price befor tax
                tableNumber:
                  type: string
                  minLength: 1
                guests:
                  type: number
                  description: Amount of guests
                staffId:
                  type: string
                  minLength: 1
                  description: 'ID of Staft, who created this bill'
                menuItems:
                  type: array
                  description: List of items that User ordered
                  items: &ref_1
                    description: Order item
                    type: object
                    title: OrderItem
                    properties:
                      productCode:
                        type: string
                        minLength: 1
                      quantity:
                        type: number
                      price:
                        type: number
                      remarks:
                        type: string
                        minLength: 1
                      productName:
                        type: string
                      productCategory:
                        type: string
                    required:
                      - productCode
                      - quantity
                      - price
                      - remarks
                      - productName
                      - productCategory
                outletID:
                  type: string
                  description: Outlet Name
                cardNumber:
                  type: string
                  description: Card number
                totalPrice:
                  type: number
                  description: Total price before tax
                totalDiscount:
                  type: number
                  description: Total of Discount
                vouchers:
                  type: array
                  description: List out all vouchers that user want to redeem
                  items: *ref_0
                payments:
                  type: array
                  description: List out all payment method user use to pay the bill
                  items: &ref_2
                    description: >-
                      The payment tender is the method by which a payment was
                      received. Cash, check, wire transfer, PayPal, credit
                      card...
                    type: object
                    properties:
                      tenderCode:
                        type: string
                        minLength: 1
                      tenderDesc:
                        type: string
                        minLength: 1
                      currencyCode:
                        type: string
                        minLength: 1
                      paymentAmount:
                        type: number
                    required:
                      - tenderCode
                      - tenderDesc
                      - currencyCode
                      - paymentAmount
                    title: Payment
              required:
                - receiptID
                - orderID
                - posNo
                - billDate
                - groundTotal
                - taxAmount
                - tableNumber
                - guests
                - staffId
                - menuItems
                - outletID
                - cardNumber
                - totalPrice
                - totalDiscount
            examples:
              example-1:
                value:
                  receiptID: string
                  orderID: string
                  posNo: string
                  billDate: string
                  groundTotal: 0
                  taxAmount: 0
                  tableNumber: string
                  guests: 0
                  staffId: string
                  menuItems:
                    - productCode: string
                      quantity: 0
                      price: 0
                      remarks: string
                      productName: string
                      productCategory: string
                  outletID: string
                  cardNumber: string
                  totalPrice: 0
                  totalDiscount: 0
                  vouchers:
                    - voucherID: string
                      voucherName: string
                      value: 0
                      voucherType: string
                      expiryDate: string
                  payments:
                    - tenderCode: string
                      tenderDesc: string
                      currencyCode: string
                      paymentAmount: 0
      security:
        - Authorization apiKey: []
    put:
      summary: Submit a sale data to CRM
      operationId: put-submit-sale
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  pointEarned:
                    type: number
                  pointRedeemed:
                    type: number
                  pointBalance:
                    type: number
                  creditBalance:
                    type: number
                  remarks:
                    type: string
                    minLength: 1
                required:
                  - pointEarned
                  - pointRedeemed
                  - pointBalance
                  - creditBalance
                  - remarks
              examples:
                example-1:
                  value:
                    pointEarned: 0
                    pointRedeemed: 0
                    pointBalance: 0
                    creditBalance: 0
                    remarks: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errorCode:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - errorCode
                  - message
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                receiptID:
                  type: string
                  minLength: 1
                orderID:
                  type: string
                  minLength: 1
                posNo:
                  type: string
                  minLength: 1
                billDate:
                  type: string
                  minLength: 1
                groundTotal:
                  type: number
                taxAmount:
                  type: number
                tableNumber:
                  type: string
                  minLength: 1
                guests:
                  type: number
                staffId:
                  type: string
                  minLength: 1
                menuItems:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items: *ref_1
                payments:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  description: List out all payment method user use to pay the bill
                  items: *ref_2
                outletID:
                  type: string
                  minLength: 1
                cardNumber:
                  type: string
                  minLength: 1
                totalPrice:
                  type: number
                totalDiscount:
                  type: number
                vouchers:
                  type: array
                  description: List out all vouchers that user want to redeem
                  items: *ref_0
              required:
                - receiptID
                - orderID
                - posNo
                - billDate
                - groundTotal
                - taxAmount
                - tableNumber
                - guests
                - staffId
                - menuItems
                - payments
                - outletID
                - cardNumber
                - totalPrice
                - totalDiscount
            examples:
              example-1:
                value:
                  receiptID: string
                  orderID: string
                  posNo: string
                  billDate: string
                  groundTotal: 0
                  taxAmount: 0
                  tableNumber: string
                  guests: 0
                  staffId: string
                  menuItems:
                    - productCode: string
                      quantity: 0
                      price: 0
                      remarks: string
                      productName: string
                      productCategory: string
                  payments:
                    - tenderCode: string
                      tenderDesc: string
                      currencyCode: string
                      paymentAmount: 0
                  outletID: string
                  cardNumber: string
                  totalPrice: 0
                  totalDiscount: 0
                  vouchers:
                    - voucherID: string
                      voucherName: string
                      value: 0
                      voucherType: string
                      expiryDate: string
      description: >-
        POS submit the transaction info to the CRM to update point, credit,
        payment history AND CLOSE TRANSACTION!
      security:
        - Authorization apiKey: []
  /redeem-voucher:
    post:
      summary: ''
      operationId: post-redeem-voucher
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: *ref_0
              examples:
                example-1:
                  value:
                    voucherID: string
                    voucherName: string
                    value: 0
                    voucherType: string
                    expiryDate: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errorCode:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - errorCode
                  - message
      description: Get Voucher information from CRM
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                voucherNumber:
                  type: string
              required:
                - voucherNumber
            examples:
              example-1:
                value:
                  voucherNumber: string
      security:
        - Authorization apiKey: []
  /redeem-credit:
    post:
      summary: ''
      operationId: post-redeem-credit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  'acceptedCreditAmount ':
                    type: number
                  creditBalance:
                    type: number
                  rejectedCreditAmount:
                    type: number
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cardNumber:
                  type: number
                creditAmount:
                  type: number
      security:
        - Authorization apiKey: []
components:
  schemas:
    Customer: *ref_3
    Payment: *ref_2
    OrderItem: *ref_1
    Voucher: *ref_0
  securitySchemes:
    Authorization apiKey:
      name: apiKey
      type: apiKey
      in: header
      description: >-
        Please get in touch with us to request a apiKey. You have to send this
        key in every request to access CRM
security:
  - Authorization with Bearer type: []
